version: '3'

services:
  source_postgres:
    container_name: source_db
    image: postgres:14
    ports:
      - "${SOURCE_PORT}:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: ${SOURCE_DB}
      POSTGRES_USER: ${SOURCE_USER}
      POSTGRES_PASSWORD: ${SOURCE_PASS}
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  elt_network:
    driver: bridge