version: '3'

services:
  source_postgres:
    container_name: source_db
    image: postgres:14
    ports:
      - "5432:${SOURCE_PORT}"
    restart: unless-stopped
    networks:
      - elt_network
    environment:
      POSTGRES_DB: "${SOURCE_DB}"
      POSTGRES_USER: "${SOURCE_USER}"
      POSTGRES_PASSWORD: "${SOURCE_PASS}"
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - source_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "${SOURCE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20

  destination_mysql:
    container_name: destination_db
    image: mysql:8.0.32
    ports: 
      - "3306:${DEST_PORT}"
    restart: unless-stopped
    networks:
      - elt_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DEST_EMPTY_ROOT_PASS} # this is purely for demo purposes. Never do this in prod
      MYSQL_DATABASE: "${DEST_DB}"
      MYSQL_USER: "${DEST_USER}"
      MYSQL_PASSWORD: "${DEST_PASS}"
    volumes:
      - destination_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  elt:
    container_name: elt_script
    build:
      context: ./elt-script
      dockerfile: ./build/Dockerfile
    networks:
      - elt_network
    depends_on:
      destination_mysql:
        condition: service_healthy
      source_postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./elt-script/elt_script:/app/elt_script
    

networks:
  elt_network:
    driver: bridge
  
volumes:
  source_database:
  destination_database: