postgres_transform:
  outputs:
    dev-docker:
      dbname: dest_db
      host: destination_db
      pass: password
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
    dev-local:
      dbname: dest_db
      host: localhost
      pass: password
      port: 5433
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev-docker
