version: 2

sources:
  - name: dest_db
    description: "Raw data from the destination PostgreSQL database."
    database: dest_db
    schema: public
    tables:
      - name: films
        description: "List of films."
        meta:
          dagster:
            asset_key: ["raw_films"]
      - name: actors
        description: "List of actors."
        meta:
          dagster:
            asset_key: ["raw_actors"]
      - name: film_actors
        description: "Mapping between films and actors."
        meta:
          dagster:
            asset_key: ["raw_film_actors"]
          
  - name: elt
    description: transfer data to the database DBT is using
    tables:
      - name: transfer_data
        meta:
          dagster:
            asset_key: ["transfer_data"]